FROM node:22-alpine as builder

WORKDIR /app

# pnpm 설치
RUN npm install -g pnpm

# package.json 복사
COPY package.json pnpm-lock.yaml ./

# 의존성 패키지 설치
RUN pnpm install

# 현재 디렉토리의 모든 파일을 도커 컨테이너의 /app 디렉토리에 복사
COPY . .

# Vite 개발 서버 환경변수 설정
ENV NODE_ENV=development
ENV PATH /app/node_module/.bin:$PATH

EXPOSE 5173

CMD ["pnpm", "run", "dev"]